#!/bin/sh
#
# Contain Environment variables for installs
#

SHARED_DIR="/vagrant"

DOWNLOAD_DIR="$SHARED_DIR/downloads"
if [ ! -d $DOWNLOAD_DIR ]; then
  mkdir $DOWNLOAD_DIR
fi

FITS_VERSION=1.5.0
FITS_PATH="${DOWNLOAD_DIR}/fits-${FITS_VERSION}"
FIREFOX_VERSION=61.0.2